### ISSUE TITLE
Not working with kafka 2.8

### ISSUE THREAD

**Issue by Maatary** [deviceinsight/kafkactl#100]
It  says  the api is not supported

**Comment by Maatary** [comment]
I'm actually using confluent version, so version 6.2.0 which is kafka 2.8

**Comment by random-dwi** [comment]
hey @Maatary,

thank you for the detailed explanation of your problem :expressionless:

I suppose you also commented [here](https://stackoverflow.com/a/65205601/1115279), which is why I assume you want to do the following:

```
# first run with --validate-only to see what kafkactl will do
kafkactl alter topic my-topic --replication-factor 2 --validate-only

# then do the replica reassignment
kafkactl alter topic my-topic --replication-factor 2
```

and you get an error: `api is not supported`

The reason for this that kafkactl does not know which kafka version your cluster is running. You have to specify it in your config.
If you do not, then we currently assume you are running version 2.0.0 (you also see this in the verbose logs). For version 2.0.0 altering the replication-factor is not supported and thats the error you get.

So you probably just have to include `kafkaVersion: 2.8.0` in your config.

btw: I will increase the default kafkaVersion to 2.5.0 for the next release, since this makese more sense in the meantime.

**Comment by Maatary** [comment]
Thank u so mucn, that solved it 👍 💯
