### ISSUE TITLE
Producer configuration

### ISSUE THREAD

**Issue by rogelio-o** [deviceinsight/kafkactl#112]
It would be great if we could add a `producer` property to the `config.yml` file so we can configure sarama client. The object could be retrieved in [CreateClientConfig](https://github.com/deviceinsight/kafkactl/blob/0e7910b1e416dab11ed454c0b510ac2a9ca78017/internal/common-operation.go#L136) for generating [sarama.Config](https://github.com/Shopify/sarama/blob/main/config.go).

I can provide a PR.

**Comment by d-rk** [comment]
Hi @rogelio-o 
which producer properties are you interested in? 
Some producer properties are already set in [producer-operation.go](https://github.com/deviceinsight/kafkactl/blob/0e7910b1e416dab11ed454c0b510ac2a9ca78017/internal/producer/producer-operation.go#L72) (`defaultPartitioner`, `requiredAcks`).

I think just adding all `producer` properties to the `config.yml` will lead to problems. If you take for example `Compression`:
the property must be customizable per topic, because compression can differ from topic to topic.

Currently we have `defaultPartitioner`, `requiredAcks` in the `config.yml` to provide a default and in addition the [produce command](https://github.com/deviceinsight/kafkactl/blob/master/cmd/produce/produce.go#L31) has parameters to overwrite the default.

**Comment by rogelio-o** [comment]
Hi @d-rk,

I am interested in `MaxMessageBytes`. Thanks!
