### ISSUE TITLE
`CGO_ENABLED=0` changes how domains are resolved on MacOS

### ISSUE THREAD

**Issue by mhaley-tignis** [deviceinsight/kafkactl#122]
Kafkactl is build with the `CGO_ENABLED=0` flags are set. My team is experimenting with using telepresence which sets up a bunch of configuration under `/etc/resolver` to direct traffic to a kafka cluster running on a remote kubernetes cluster, which are ignored with that flag is set at build time. I built kafkactl from source at the latest release commit without the flag and things work as expected. Is there any reason this flag is set? So far the tool works as expected with it not set.

I also opened a related issue here https://github.com/golang/go/issues/51753

**Comment by d-rk** [comment]
Hey @mhaley-tignis,

we use [goreleaser](https://goreleaser.com) for our release process and at the time we started using it, it did not support CGO enabled builds because of cross-compilation issues.
Currently, it is not longer said that it is not supported, but it comes with some limitations. see: https://goreleaser.com/limitations/cgo/

Because of this we will leave the flag in place, but you should not run into problems when building from source, except when you try to cross-compile the code.
