### ISSUE TITLE
Expose compression used for message [Feature request]

### ISSUE THREAD

**Issue by matthew-hollick** [deviceinsight/kafkactl#142]
Hello 👋 

We have recently implemented producer side compression of messages sent to Kafka.
Given that most of the clients are owned by other teams we can only have so much confidence that they have all implemented compression correctly.
I would love to be able to sample data from the brokers to test for messages that are uncompressed or "compressed but with an unexpected algorithm".
We do not have access to the filesystem on the brokers.

Any thoughts?

**Comment by d-rk** [comment]
Hey @matthew-hollick 
we don't have that information, because it is encapsulated in the  https://github.com/Shopify/sarama lib.
Did you enable compression on topic level? This will guarantee you the desired compression, but with additional (re-)compression overhead on the broker if the producer has an incorrect compression configured.

**Comment by matthew-hollick** [comment]
@d-rk 
Thanks for the response.
I was kind of worried that information might be abstracted.
Reducing the network traffic from Producer to Kafka is our primary goal as there is a cost per MB of data transferred.
Enabling Broker based compression is an interesting option but we are kind of low level scared that a single customer having their compression set wrong could blow the brokers out of the water for everybody.
I will close the ticket.

Regards,

Matthew.
