### ISSUE TITLE
Snap can't load config

### ISSUE THREAD

**Issue by hho** [deviceinsight/kafkactl#19]
The Snap version is basically unusable, because it can't read its configuration file.

kafkactl attempts to read configs from:

* `/etc/kafkactl/config.yml`
  but Snap doesn't allow access outside the home directory of the user

* `~/.kafkactl/config.yml`
  but Snap doesn't allow access to hidden files inside the home directory either

I'd suggest adding another searched config path (e.g. `~/kafkactl/config.yml`). It needs to be in the users home directory and it must not be a hidden file.

<details>
<summary>P.S.</summary>
Why have a directory at all? Why isn't it <tt>~/kafkactl.yml</tt> and <tt>/etc/kafkactl.yml</tt>?
</details>

<details>
<summary>P.P.S.</summary>
I don't exactly get how Viper works – does it load only the first found? In that case you should probably reverse the order so a user-specific config has precedence over a global one. However, if all files are loaded, then the order is correct, as latter settings override former ones.
</details>

**Comment by dwi-di** [comment]
I only tested the snap package on Fedora an there it works, but you are correct that it has to be changed to work correctly.
If I remember correctly @stefan-hudelmaier proposed to use the `kafkactl` folder in order to match closer to how kubectl defines the config file.

We should probably use the following order:
* first check snap folders (https://docs.snapcraft.io/environment-variables/7983)
** check if $SNAP_USER_COMMON is available and look inside there for a `config.yml`
** check if $SNAP_COMMON is available and look inside there for a `config.yml`
* then check `~/.config/kafkactl/config.yml` (https://stackoverflow.com/a/1024339/1115279)
* finally check `/etc/kafkactl/config.yml`

what do you think @hho ?

the current implementation only loads the first config file found, so we should load the global one last.

**Comment by hho** [comment]
First of all: **I'm an idiot**. It works, if I use the "redirected" home folder…

However, according to the Snapcraft docs you kindly linked to, the `$SNAP_USER_COMMON`/`$SNAP_COMMON` are **not** suitable, because they get lost in a `snap refresh`/`snap revert`.

The ones to choose seem to be `$SNAP_USER_DATA`/`$SNAP_DATA`. But `$SNAP_USER_DATA` is identical to the redirected `$HOME`, so the correct search order seems to be:

1. `$HOME/.config/kafkactl/config.yml` (location according to XDG)
2. `$HOME/.kafkactl/config.yml` (location similar to kubectl; kept for backwards compatibility)
3. `$SNAP_DATA/kafkactl/config.yml` (system-wide snap config)
4. `/etc/kafkactl/config.yml` (system-wide regular config)

And finally: An alternative to all of the above would be to make kafkactl a `--classic` mode Snap. Then all directories would be accessible, and you might want to do that in the future anyway (e.g. to produce messages from a file anywhere). Kubectl does this. The downside would be the imposed review process.

**Comment by dwi-di** [comment]
I implemented the additional config file locations in https://github.com/deviceinsight/kafkactl/commit/37ece7493ddd7a2d56a90f56efade75c8a5314b1

I think we should avoid using snaps `--classic` mode for now. It is not really needed.
Producing should already work with any file since one usually uses cat for that e.g.:
`cat my-file | kafkactl produce my-topic`
