### ISSUE TITLE
Add parameter --rate to produce command

### ISSUE THREAD

**Issue by dwi-di** [deviceinsight/kafkactl#28]
add a parameter `--rate` which controls the rate with which messages are produced.
this is useful to limit the number of produced messages when inserting messages on a production environment.
`--rate` should be an integer that represents the number of messages that should be produced per second.

**Comment by georgettica** [comment]
I really want to own this Issue :)
Thanks :/

**Comment by dwi-di** [comment]
its yours ;)

**Comment by georgettica** [comment]
Hey!
I got to the code at last and decided to use golangs way to rate limit 'https://github.com/golang/go/wiki/RateLimiting'

I will be adding the code to `producer-operations.go`
I will need to add the option to the command line in produce.go but ill do that after the core login.

I hope I am on the right track

**Comment by georgettica** [comment]
I can add the parameter, but it seems from the docs and the code I understood that there is no bulk message sending..
where does that happen?

**Comment by random-dwi** [comment]
Producing many Messages to a topic should be done similar to this:
```
cat file.json | kafkactl produce my-topic --separator=#
``` 
The Messages are passed via stdin here:
https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/producer-operation.go#L94

But as i see it now, this does Not allow processing of multiple messages.

It would need to bei changed so that:
- not all ist read from stdin
- but it is read line by line
- then the rate limiting could also be applied

If you need help with that. Let me know.

**Comment by georgettica** [comment]
I will upload a partial PR soon so we have a common place to talk about the issue, but I think that there are some edge cases to be addressed, I'll highlight them with comments
