### ISSUE TITLE
JSON Pretty Print

### ISSUE THREAD

**Issue by antonkomarev** [deviceinsight/kafkactl#54]
It would be great to have additional flag for the `kafkactl consume` to display pretty printed JSON.

Raw JSON:
```json
{"type":"UserStatusChanged","id":"e886eb90-4003-4b1f-9971-8f4bdb23dc89","timestamp":1588167444,"data":{"user":{"id":331,"status":"approved"},"from_status":"created","to_status":"approved","changed_at":"2020-04-29T13:37:18+00:00"}}
```

Pretty printed JSON:
```json
{
  "type": "UserStatusChanged",
  "id": "e886eb90-4003-4b1f-9971-8f4bdb23dc89",
  "timestamp": 1588167444,
  "data": {
    "user": {
      "id": 331,
      "status": "approved"
    },
    "from_status": "created",
    "to_status": "approved",
    "changed_at": "2020-04-29T13:37:18+00:00"
  }
}
```

It might be useful on development phase for debugging the messages.

**Comment by random-dwi** [comment]
@antonkomarev the consume command has a flag `--output` which controls if the output should be plain text, json or yaml. But this controls printing of the whole kafka message object including parameters like offset, partition, etc. You are probably talking about a json formatted message.
if you use `-o json` then your json message value would be escaped, so this won't help.
But since you are working with json, you probably also have `jq` installed.

You can just do:
```
kafkactl consume my-topic | jq .
```
 to get your message pretty printed.

**Comment by antonkomarev** [comment]
Thank you very much, it works!

```shell script
kafkactl consume my-topic | jq .
```
