### ISSUE TITLE
Docker image does not include CA certificates

### ISSUE THREAD

**Issue by MadsRC** [deviceinsight/kafkactl#63]
First off: Great work on allowing us to configure Kafkactl using environment variables! Makes the tool very useable with Amazon MSK

The issue:
You provided docker image does not seem to include any CA certificates. In order to connect to a TLS host (In this case an Amazon MSK cluster using certificates provided by Amazon) one needs to either set TLS_INSECURE=true or TLS_CA=/path/to/provided/ca.

Unfortunately, in my use-case, adding the CA certificate manually does not work very well, as the container is running on a remote host (and is launched ad-hoc).

Using the TLS_INSECURE=true is a workaround, but not optimal, especially not for production.

Command example:
```
user@machine dsp % kubectl run -i --tty --rm kafkactl --image=deviceinsight/kafkactl:latest --restart=Never --env="TLS_ENABLED=true" --env="BROKERS=$(aws --profile saml kafka get-bootstrap-brokers --cluster-arn $(aws --profile saml kafka list-clusters --cluster-name-filter 'msk' --query 'ClusterInfoList[0].{arn:ClusterArn}' | jq -r .arn) | jq -r .BootstrapBrokerStringTls | sed 's/,/ /g')" -- kafkactl -V get topics
If you don't see a command prompt, try pressing enter.
[sarama  ] 2020/09/19 20:49:42 client/metadata fetching metadata for all topics from broker b-3.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:49:42 Failed to connect to broker b-3.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata got error from broker -1 while fetching metadata: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata fetching metadata for all topics from broker b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:49:42 Failed to connect to broker b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata got error from broker -1 while fetching metadata: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata fetching metadata for all topics from broker b-1.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:49:42 Failed to connect to broker b-1.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata got error from broker -1 while fetching metadata: x509: certificate signed by unknown authority
[sarama  ] 2020/09/19 20:49:42 client/metadata no available broker to send metadata request to
[sarama  ] 2020/09/19 20:49:42 client/brokers resurrecting 3 dead seed brokers
[sarama  ] 2020/09/19 20:49:42 Closing Client
failed to create cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
pod "kafkactl" deleted
pod default/kafkactl terminated (Error)
user@machine dsp % kubectl run -i --tty --rm kafkactl --image=deviceinsight/kafkactl:latest --restart=Never --env="TLS_INSECURE=true" --env="TLS_ENABLED=true" --env="BROKERS=$(aws --profile saml kafka get-bootstrap-brokers --cluster-arn $(aws --profile saml kafka list-clusters --cluster-name-filter 'msk' --query 'ClusterInfoList[0].{arn:ClusterArn}' | jq -r .arn) | jq -r .BootstrapBrokerStringTls | sed 's/,/ /g')" -- kafkactl -V get topics
[kafkactl] 2020/09/19 20:50:11 generated default config at /home/kafkactl/.config/kafkactl/config.yml
[kafkactl] 2020/09/19 20:50:11 Using config file: /home/kafkactl/.config/kafkactl/config.yml
[kafkactl] 2020/09/19 20:50:11 Assuming kafkaVersion: 2.0.0
[kafkactl] 2020/09/19 20:50:11 Assuming kafkaVersion: 2.0.0
[kafkactl] 2020/09/19 20:50:11 TLS is enabled.
[sarama  ] 2020/09/19 20:50:11 Initializing new client
[sarama  ] 2020/09/19 20:50:11 client/metadata fetching metadata for all topics from broker b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 Connected to broker at b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094 (unregistered)
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #5 at b-5.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #4 at b-4.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #1 at b-1.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #6 at b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #2 at b-2.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 client/brokers registered new broker #3 at b-3.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:11 Successfully initialized new client
[kafkactl] 2020/09/19 20:50:11 TLS is enabled.
[sarama  ] 2020/09/19 20:50:11 Initializing new client
[sarama  ] 2020/09/19 20:50:11 client/metadata fetching metadata for all topics from broker b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 Connected to broker at b-3.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094 (registered as #3)
[sarama  ] 2020/09/19 20:50:12 Connected to broker at b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094 (unregistered)
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #5 at b-5.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #4 at b-4.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #1 at b-1.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #6 at b-6.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #2 at b-2.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 client/brokers registered new broker #3 at b-3.msk.jp2jsm.c4.kafka.eu-west-1.amazonaws.com:9094
[sarama  ] 2020/09/19 20:50:12 Successfully initialized new client
TOPIC                  PARTITIONS
__consumer_offsets     50
pod "kafkactl" deleted
```
Please consider installing CA certificates to the docker ubuntu image. It should only use around 5801kB more space.

**Comment by random-dwi** [comment]
Hey @MadsRC,
That's a valid point and your PR should fix the issue for your usecase.
We are trying to simplify working with kafka clusters accessible only from within kubernetes. We added support for this although it is still experimental.
See: https://github.com/deviceinsight/kafkactl#running-in-kubernetes

This currently does not work when kafkactl is installed via snap. But please try it out and let us know what is missing so that you can use this instead of manually executing `kubectl exec`.
In any case we would have to add two things:
- the change from your PR also has to be done for the scratch docker image. Probably with a builder like it is done here: https://github.com/chemidy/smallest-secured-golang-docker-image/blob/master/Dockerfile
- if the config contains a custom cert it has to be mounted as a volume into the docker container in order to work.

**Comment by MadsRC** [comment]
The running-in-kubernetes feature seems neat - I'll definitely look into it!

I haven't worked with scratch images before, but that just makes it more fun. I'll see what I can do about adding it - Do you want it in the same PR?

Regarding the second point - I suppose I could add some logic that looks for certs in a specific folder and updates the OS certificate store if any is found in that folder? That would just require that the location is documented, and users would be able to add their own certificates by simply mounting them as a volume - Is this what you meant?

**Comment by MadsRC** [comment]
Looking at it, it seems like adding the "globally" trusted CA's to the scratch image is straight forward with the builder approach you linked.

I think I can cook something up and add it to the pull request. There's a few issues that pop into my head though, specifically related to supporting users that want to add a custom CA cert (Which is a valid use-case IMHO)

1. It is easily doable if they mount it directly into `/etc/ssl/certs/ca-certificates.crt` - The issue here is that they would trust that specific CA (Which can be considered as a security feature...) - If this is acceptable, we should simply document this fact.

2. If you want to support users adding their custom CA, but still trust the CA's included in the image, you can either copy in the `update-ca-certificates` binary and all it's dependencies, or find/code some static binary that emulates the behaviour we need. Then, during container startup, a routine would look for certificates in a specific location (To which the user can mount a volume containing certificates) and run either `update-da-certificates` or some custom code that will add those CA's to `/etc/ssl/certs/ca-certificates.crt`.

Let me know if any of it makes any sense, or if it misses the entire point of what you meant with the config containing a custom cert.

**Comment by random-dwi** [comment]
1. for the globally trusted CA's I would be glad if you could add them to the scratch image as well. You can do that in your open PR.
2. adding custom CA should not be that complicated. We don't have to run `update-ca-certificates` or copy them to `/etc/ssl/...` since in the code we already support reading a custom ca from an arbitrary location (set in the config yml) and use that ca (https://github.com/deviceinsight/kafkactl/blob/master/operations/common-operation.go#L207).
The only remaining problem is that when running in docker the location of the custom ca is on the docker host, so we have to mount that volume in the docker container and then add the env variable `TLS_CA` with the CA from the mounted location. This is straight forward with docker, but mounting volumes with `kubectl run` is a bit of a hassle. I will look into this myself

**Comment by MadsRC** [comment]
I’ll add it to the scratch image, no problem.

Custom CA: Yes, of course... Talk about not seeing the forest for the trees... Prime example of why one should not necessarily implement ones first thought ;)

I wouldn’t mind working on it though, if you there’s more pressing matters to tend to in the codebase? I’ve got some free time and might as well spend it on an OSS project ;)

**Comment by random-dwi** [comment]
@MadsRC sorry for the delayed response, but I've been quite busy lately.
Your PR looked good and I already merged it.

Currently the most urgent issue is https://github.com/deviceinsight/kafkactl/issues/61.
Installing via snap is the easiest way to start with kafkactl for many users. But for the kubernetes feature to work in kafkactl we have to change the implementation. Currently we just [execute](https://github.com/deviceinsight/kafkactl/blob/master/operations/k8s/executor.go#L137) a `kubectl` binary and forward the commandline parameters. Thats not possible with snap since we are in a sandbox.
Instead we have to use the [kubernetes go-client](https://github.com/kubernetes/client-go) so that we do not have to execute an external binary.
I don't know if you feel confident with working on this, but that would be a great help for us.
