### ISSUE TITLE
Using SSL keystore and Truststore

### ISSUE THREAD

**Issue by michaelburris** [deviceinsight/kafkactl#65]
Thanks for the awesome tool.

How would I go about passing in a configuration like this?

example.properties file
```
security.protocol=SSL
ssl.truststore.location=
ssl.truststore.password=
ssl.keystore.location=
ssl.keystore.password=
ssl.key.password=
```

This is an example properties file that I would normally pass into a kafka command like this 
```
kafka-topics --bootstrap-server broker1  \
--command-config /path/to/example.properties \
--topic some-topic \
--describe
```

**Comment by random-dwi** [comment]
Hey @michaelburris,

ok let me try to break it down:

The truststore contains certificates you (the client) trusts. `ssl.truststore.location` will point to a `.jks` file I guess and `ssl.truststore.password` is the corresponding password.
kafkactl uses the config `tls.ca` to configure trusted certificates. the configuration expects a file in pem format. You need to convert your truststore to a pem file. This can be done using keytool [(probably like this)](https://stackoverflow.com/a/40194333/1115279) or if you prefer a gui using [keystore explorer](https://keystore-explorer.org/).

the keystore contains private-key/certificate pair, and the broker uses the certificate to authenticate the client.
kafkactl uses separate configs `tls.certKey`, `tls.cert` for the key/certificate pair. Since they are also expected in pem format, you will need to convert the keystore to separate pem files for key/certificate. This can again be done using keytool or keystore explorer.
