### ISSUE TITLE
Kafkactl hangs on Deserialize error and never exits.

### ISSUE THREAD

**Issue by mhaley-miovision** [deviceinsight/kafkactl#77]
Problem
---
When I run `kafkactl consume <topic-name>` with schema registry enabled, kafkactl fails to parse the avro message (I don't know why, I am still debugging that), but when I hit ctrl+c, the process just hangs.

Breakdown
---
Based on what I have been able to debug, the program is getting hung up on this line https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L164. Because the deserializer is no longer consuming messages, that loop is waiting to post a message to the buffer, and so the closing channel signal [here](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L177-L180) is never read. This means the function never returns so the [defer](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L155) is never called and we never get past the [consumer wait](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L225).

When I fixed that problem using the following code:
```
select {
  case messages <- message: // Put message in the channel unless it is full
  default:
	  output.Debugf("Message Buffer is full. Discarding value.")
	  pc.AsyncClose()
	  break messageChannelRead
}					
```
we get caught at the next wait statement, which means that [this defer](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L214) is never being called because the [error channel](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L218) is full. My solution there was to increase the size of the error channel [here](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L114)
```
errChannel        = make(chan error, 100)
```

Once I resolved that the program now exits and I see my error in the console. I feel like what I have done is a workaround to the problem. Just dropping messages on the floor and exiting seems like a bad route to take (see first code snippet). Additionally, refering to https://stackoverflow.com/a/25657232, if we used the len(chan) function, you could get into nasty race conditions.

**Comment by random-dwi** [comment]
Hey @mhaley-miovision, thank you for the detailed analysis.
I haven't had time to check this in detail but I suspect that this [return](https://github.com/deviceinsight/kafkactl/blob/233200cf6d6dec2557ffa79693ba20372f09cdc9/operations/consumer/consumer-operation.go#L219) statement is the root cause. It causes the routine to stop reading the `messages` channel directly after an error and since the consumer is still putting new messages in the channel we run into this waiting forever issue. What do you think?

**Comment by mhaley-miovision** [comment]
> I haven't had time to check this in detail but I suspect that this [return](https://github.com/deviceinsight/kafkactl/blob/233200cf6d6dec2557ffa79693ba20372f09cdc9/operations/consumer/consumer-operation.go#L219) statement is the root cause. It causes the routine to stop reading the `messages` channel directly after an error and since the consumer is still putting new messages in the channel we run into this waiting forever issue. What do you think?

Hey @random-dwi, if we remove the return statement there, then the consumer will continue to deserialize and eventually fill the errChannel and get stuck there, leading to the same problem.

If we do something like
```
	go func() {
		for err := range errChannel {
			output.Fail(err)
		}
	}()
```
for reading off of the error channel, the program will exit when it encounters an error. However, there is still a race condition in here somewhere, because when I set the option `--tail` the program will sometimes exit code 1, but other times exit code 0, which seems undesirable.

In general, this function is very complicated and I would recommend a refactor to limit the number of channels and/or wait groups that there are. That would simplify this chunk of code https://github.com/deviceinsight/kafkactl/blob/233200cf6d6dec2557ffa79693ba20372f09cdc9/operations/consumer/consumer-operation.go#L225-L231, and reduce the number of potential race conditions too. For example, the [messageChannel](https://github.com/deviceinsight/kafkactl/blob/master/operations/consumer/consumer-operation.go#L164) from the sarama consumer is already buffered, there really isn't much benefit in buffering it again, so you could call the deserialize function in line and completely remove the need for the `messages` channel altogether.

**Comment by random-dwi** [comment]
Hey @mhaley-miovision,
I did not mean that deleting the `return` is the solution, but whats causing the infinite wait.
I know that the function is quite complicated, but currently I don't see a good way to simplify it. If you want to propose a refactoring just create a PR. 
The `messages` channel is not buffered, the corresponding `bufferSize` parameter was just a left-over (which is always 0) and I removed it with #80.
We do not deserialize from the sarama messageChannel directly because that is a channel per partition and for the `--tail` parameter to work, we need to have messages from different partitions together in one place.
