### ISSUE TITLE
It is not working with latest kubectl

### ISSUE THREAD

**Issue by renatojf** [deviceinsight/kafkactl#82]
```
$ kafkactl get topics
Error: unknown flag: --generator
See 'kubectl run --help' for usage.
command "/usr/local/bin/kubectl" exited with non-zero status:

PATH:
  /usr/local/bin/kubectl
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
```

Am I doing something wrong? It used to work and it stopped recently.

**Comment by random-dwi** [comment]
hey @renatojf,

You can run `kafkactl get topics -V` to see the actually kubectl command being invoked.
The problem here is that for `kubectl run` the `--generator` parameter was removed in newer kubectl version.

The parameter is set here: https://github.com/deviceinsight/kafkactl/blob/master/operations/k8s/executor.go#L108 
Since we run a pod, and thats the only thing `kubectl run` in newer versions can spawn, we can just remove this `--generator` parameter in the code.

I'm currently quite busy, so it will take a while unless you want to provide a PR for this.

**Comment by renatojf** [comment]
@random-dwi https://github.com/deviceinsight/kafkactl/pull/83
👍

**Comment by renatojf** [comment]
@random-dwi Thanks for the reply. 👍

**Comment by VincentAuguin** [comment]
Hi, I'm facing the same issue with kubectl 1.21.0. When can we expect the PR being merged ?

**Comment by random-dwi** [comment]
I don't have time to look into this before mid of the upcoming week.

**Comment by random-dwi** [comment]
@renatojf @VincentAuguin a new version with the fix was just released. Sorry for the delay.

**Comment by renatojf** [comment]
Thank you so much @random-dwi 👍
