### ISSUE TITLE
Delete a consumer group

### ISSUE THREAD

**Issue by cykl** [deviceinsight/kafkactl#89]
kafkactl doesn't seems able to delete a consumer group (ex. `kafka-consumer-group --delete --group my_group`).  Adding `kafkactl delete consumer-group` would be very useful as deleting a consumer group is a common operation (ex. application decommissioning).

**Comment by random-dwi** [comment]
hey @cykl,

this one should be rather easy to implement. the related api in sarama is already there:
https://github.com/Shopify/sarama/blob/master/admin.go#L99

The implementation is basically the same like for topic deletion except, that the final call to the admin client has to be a different one.
PR for this is also welcomed, since I cannot predict when we will have time for this.

**Comment by cykl** [comment]
Thanks for the feedback :+1: 

>  since I cannot predict when we will have time for this.

I share the same issue (plus not being fluent in Go). I will notify here if I found some free time to work but it's better not to count on that happening.

**Comment by mumrau** [comment]
Hello.

Thank you for the feature, really enjoyable.
I have just noticed a minor issue: the help message hasn't been updated, `kafkactl -h` still shows
```
  create      create topics, consumerGroups, acls
  delete      delete topics, acls
```
Instead of 
``` 
  delete      delete topics, consumerGroups, acls
```

**Comment by random-dwi** [comment]
@mumrau thank you for the hint. I updated the the command help accordingly.
