### ISSUE TITLE
produced messages rejected

### ISSUE THREAD

**Issue by krisek** [deviceinsight/kafkactl#90]
Apologies for the `r=1` issue, but I cannot find any relevant trace of solution for my problem. 

When I try to produce messages with `kafkactl`, I always get an error message:

```
root@kubectl /# kafkactl produce hello-world -v hello
Failed to produce message: kafka server: Messages are rejected since there are fewer in-sync replicas than required.
```

Producing into the very same topic with kafka-console-producer.sh works without any issue.

```
root@kubectl ~/k/bin# ./kafka-console-producer.sh --broker-list b-1.*****.c4.kafka.eu-central-1.amazonaws.com:9096,b-3.*****.c4.kafka.eu-central-1.amazonaws.com:9096,b-2.*****.c4.kafka.eu-central-1.amazonaws.com:9096 --topic hello-world --producer.config client_sasl.properties
>hello
```

Any ideas what this can be?

**Comment by random-dwi** [comment]
Hey @krisek,

this is caused by this setting here:
https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/producer-operation.go#L67

Which in turn is explained here:
https://pkg.go.dev/github.com/Shopify/sarama?utm_source=godoc#RequiredAcks

This should probably be changed:
- we should not set a default for this and rather use the sarama default (WaitForLocal) in order to align with the jvm producer
- we should add a configuration option to make it configurable

**Comment by krisek** [comment]
🙏 thanks a lot for fixing this
